spring:
    jpa:
        database: MYSQL
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
                generate_statistics: true

    datasource:
        url: jdbc:mysql://localhost:3306/testdb?useSSL=false
        username: root
        password: secret
        initialization-mode: always

#    h2:
#        console:
#            enabled: true

logging:
  file: teszt.log

security:
  token:
    maxAgeSecond: 86400
    secret: TesztElem


#logging:
#  level:
#    org:
#      hibernate:
#        type: debug

